from infrastructure.core_bridge_adapters import CoreBridgeAdapter
from infrastructure.core_dependency_injection_factories import CoreDependencyInjectionFactoryJson
from domain.usecases import GetInjection
from domain.models import Inventory
