from infrastructure.core_bridge_adapters import CoreBridgeAdapter
from infrastructure.core_dependency_injection_factories import CoreDependencyInjectionFactoryJson
from domain.usecases.get_injection import GetInjection
from infrastructure.inventory_repositories import InventoryRepositoryMySQL
from domain.usecases.get_database_controller import GetDatabaseController